### ISSUE TITLE
German translation for "open" in dialogs is nonsense

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode-loc#117]
https://github.com/microsoft/vscode-loc/blob/12060709a69f4d6953a0db580eaa7f9571cd10af/i18n/vscode-language-pack-de/translations/main.i18n.json#L1182

This was allegedly fixed in https://github.com/microsoft/vscode/issues/77267 but I still see the wrong translation here and in the latest version of VSCode.

/cc @lukaschal

**Comment by lukaschal** [comment]
Fixed.

**Comment by AlCalzone** [comment]
How long does it usually take until updated translations are included in a VSCode build? 1.39.2 does not have this fix yet.

**Comment by janbaltus** [comment]
Please use 1.40.2 version of Language pack
![image](https://user-images.githubusercontent.com/18324209/68382045-2f8e7500-0153-11ea-814f-03c4e6357916.png)

**Comment by AlCalzone** [comment]
Great!

**Comment by stephtr** [comment]
The translation is still wrong for "vs/workbench/contrib/url/common/trustedDomainsValidator/open". Could someone fix that on the Translation Community?

**Comment by janbaltus** [comment]
this one occurrence was fixed. Will be present in January update of VScode LP
